# Comprehensive Spanish to English translation for documentation
# Handles most common phrases from the project

$translations = @{
    # Common keywords
    "Bloque" = "Block"
    "bloque" = "block"
    "Completado" = "Completed"
    "completado" = "completed"
    "COMPLETADO" = "COMPLETED"
    "Entrega" = "Delivery"
    "entrega" = "delivery"
    "ENTREGA" = "DELIVERY"
    "Verificación" = "Verification"
    "verificación" = "verification"
    "VERIFICACIÓN" = "VERIFICATION"
    "Cierre" = "Closure"
    "cierre" = "closure"
    "CIERRE" = "CLOSURE"
    "Documentación" = "Documentation"
    "documentación" = "documentation"
    "DOCUMENTACIÓN" = "DOCUMENTATION"
    "Arquitectura" = "Architecture"
    "arquitectura" = "architecture"
    "ARQUITECTURA" = "ARCHITECTURE"
    "Resumen" = "Summary"
    "resumen" = "summary"
    "RESUMEN" = "SUMMARY"
    "Ejecutivo" = "Executive"
    "ejecutivo" = "executive"
    "EJECUTIVO" = "EXECUTIVE"
    "Proyecto" = "Project"
    "proyecto" = "project"
    "PROYECTO" = "PROJECT"
    "Guía" = "Guide"
    "guía" = "guide"
    "GUÍA" = "GUIDE"
    "Rápida" = "Quick"
    "rápida" = "quick"
    "RÁPIDA" = "QUICK"
    "Estado" = "Status"
    "estado" = "status"
    "ESTADO" = "STATUS"
    "Checklist" = "Checklist"
    "checklist" = "checklist"
    "CHECKLIST" = "CHECKLIST"
    "Publicación" = "Publication"
    "publicación" = "publication"
    "PUBLICACIÓN" = "PUBLICATION"
    "Packagist" = "Packagist"
    "packagist" = "packagist"
    "PACKAGIST" = "PACKAGIST"
    
    # Common phrases
    "Estructura completa" = "Complete structure"
    "Estructura del Proyecto" = "Project Structure"
    "estructura del proyecto" = "project structure"
    "Requisito" = "Requirement"
    "requisito" = "requirement"
    "REQUISITO" = "REQUIREMENT"
    "Requisitos" = "Requirements"
    "requisitos" = "requirements"
    "REQUISITOS" = "REQUIREMENTS"
    "Detalles" = "Details"
    "detalles" = "details"
    "DETALLES" = "DETAILS"
    "Notas" = "Notes"
    "notas" = "notes"
    "NOTAS" = "NOTES"
    "Nota" = "Note"
    "nota" = "note"
    "NOTA" = "NOTE"
    "Explicación" = "Explanation"
    "explicación" = "explanation"
    "EXPLICACIÓN" = "EXPLANATION"
    "Test" = "Test"
    "test" = "test"
    "TEST" = "TEST"
    "Prueba" = "Test"
    "prueba" = "test"
    "PRUEBA" = "TEST"
    "Diseño" = "Design"
    "diseño" = "design"
    "DISEÑO" = "DESIGN"
    "Interfaz" = "Interface"
    "interfaz" = "interface"
    "INTERFAZ" = "INTERFACE"
    "Implementación" = "Implementation"
    "implementación" = "implementation"
    "IMPLEMENTACIÓN" = "IMPLEMENTATION"
    "Extracción" = "Extraction"
    "extracción" = "extraction"
    "EXTRACCIÓN" = "EXTRACTION"
    "Estructuración" = "Structuring"
    "estructuración" = "structuring"
    "ESTRUCTURACIÓN" = "STRUCTURING"
    "Validación" = "Validation"
    "validación" = "validation"
    "VALIDACIÓN" = "VALIDATION"
    "Error" = "Error"
    "error" = "error"
    "ERROR" = "ERROR"
    "Errores" = "Errors"
    "errores" = "errors"
    "ERRORES" = "ERRORS"
    "Advertencia" = "Warning"
    "advertencia" = "warning"
    "ADVERTENCIA" = "WARNING"
    "Advertencias" = "Warnings"
    "advertencias" = "warnings"
    "ADVERTENCIAS" = "WARNINGS"
    "Información" = "Information"
    "información" = "information"
    "INFORMACIÓN" = "INFORMATION"
    "Contenido" = "Content"
    "contenido" = "content"
    "CONTENIDO" = "CONTENT"
    "Éxito" = "Success"
    "éxito" = "success"
    "ÉXITO" = "SUCCESS"
    "Exitoso" = "Successful"
    "exitoso" = "successful"
    "EXITOSO" = "SUCCESSFUL"
    "Exitosamente" = "Successfully"
    "exitosamente" = "successfully"
    "EXITOSAMENTE" = "SUCCESSFULLY"
    "Funcional" = "Functional"
    "funcional" = "functional"
    "FUNCIONAL" = "FUNCTIONAL"
    "Compatibilidad" = "Compatibility"
    "compatibilidad" = "compatibility"
    "COMPATIBILIDAD" = "COMPATIBILITY"
    "Compatible" = "Compatible"
    "compatible" = "compatible"
    "COMPATIBLE" = "COMPATIBLE"
    "Cambios" = "Changes"
    "cambios" = "changes"
    "CAMBIOS" = "CHANGES"
    "Cambio" = "Change"
    "cambio" = "change"
    "CAMBIO" = "CHANGE"
    "Próximos" = "Next"
    "próximos" = "next"
    "PRÓXIMOS" = "NEXT"
    "Próximo" = "Next"
    "próximo" = "next"
    "PRÓXIMO" = "NEXT"
    "Funcionamiento" = "Operation"
    "funcionamiento" = "operation"
    "FUNCIONAMIENTO" = "OPERATION"
    "Estadísticas" = "Statistics"
    "estadísticas" = "statistics"
    "ESTADÍSTICAS" = "STATISTICS"
    "Estadística" = "Statistic"
    "estadística" = "statistic"
    "ESTADÍSTICA" = "STATISTIC"
}

# Get all .md files
$mdFiles = Get-ChildItem -Path "." -Filter "*.md" -Exclude "*.bak"

Write-Host "Starting content translation of $($mdFiles.Count) markdown files..."

foreach ($file in $mdFiles) {
    $originalContent = Get-Content $file.FullName -Raw
    $translatedContent = $originalContent
    
    foreach ($spanish in $translations.Keys) {
        $english = $translations[$spanish]
        $translatedContent = $translatedContent -Replace [regex]::Escape($spanish), $english
    }
    
    if ($translatedContent -ne $originalContent) {
        Set-Content -Path $file.FullName -Value $translatedContent -Encoding UTF8
        Write-Host "✓ Translated: $($file.Name)"
    }
}

Write-Host "Translation complete!"
